# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'principal.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import archivos
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Principal(object):
    def setupUi(self, Principal):
        Principal.setObjectName("Principal")
        Principal.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        Principal.setFont(font)
        self.centralwidget = QtWidgets.QWidget(Principal)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menuIzquierdo = QtWidgets.QFrame(self.frame_2)
        self.menuIzquierdo.setMinimumSize(QtCore.QSize(50, 0))
        self.menuIzquierdo.setMaximumSize(QtCore.QSize(50, 16777215))
        self.menuIzquierdo.setStyleSheet("QFrame{\n"
                                         "background:  #664E88;\n"
                                         "}")
        self.menuIzquierdo.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menuIzquierdo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuIzquierdo.setObjectName("menuIzquierdo")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.menuIzquierdo)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_5 = QtWidgets.QFrame(self.menuIzquierdo)
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.btnMenu = QtWidgets.QPushButton(self.frame_5)
        self.btnMenu.setGeometry(QtCore.QRect(0, 0, 180, 50))
        self.btnMenu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnMenu.setStyleSheet("QPushButton{\n"
                                   "border:none;\n"
                                   "background: transparent;\n"
                                   "padding:10px;\n"
                                   "text-align:left;\n"
                                   "}")
        self.btnMenu.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Iconos/Iconos/Menu.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnMenu.setIcon(icon)
        self.btnMenu.setIconSize(QtCore.QSize(30, 30))
        self.btnMenu.setObjectName("btnMenu")
        self.verticalLayout_2.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.menuIzquierdo)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.btnPrincipal = QtWidgets.QPushButton(self.frame_6)
        self.btnPrincipal.setGeometry(QtCore.QRect(0, 30, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.btnPrincipal.setFont(font)
        self.btnPrincipal.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPrincipal.setStyleSheet("QPushButton{\n"
                                        "border:none;\n"
                                        "background: transparent;\n"
                                        "color: #fff;\n"
                                        "padding:10px;\n"
                                        "text-align: left;\n"
                                        "}\n"
                                        "QPushButton:hover{\n"
                                        "background: #4B3869\n"
                                        "}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Iconos/Iconos/Principal.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPrincipal.setIcon(icon1)
        self.btnPrincipal.setIconSize(QtCore.QSize(30, 30))
        self.btnPrincipal.setObjectName("btnPrincipal")
        self.btnUsuarios = QtWidgets.QPushButton(self.frame_6)
        self.btnUsuarios.setGeometry(QtCore.QRect(0, 100, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.btnUsuarios.setFont(font)
        self.btnUsuarios.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnUsuarios.setStyleSheet("QPushButton{\n"
                                       "border:none;\n"
                                       "background: transparent;\n"
                                       "color: #fff;\n"
                                       "padding:10px;\n"
                                       "text-align: left;\n"
                                       "}\n"
                                       "QPushButton:hover{\n"
                                       "background: #4B3869\n"
                                       "}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Iconos/Iconos/Usuario.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnUsuarios.setIcon(icon2)
        self.btnUsuarios.setIconSize(QtCore.QSize(30, 30))
        self.btnUsuarios.setObjectName("btnUsuarios")
        self.btnConfiguracion = QtWidgets.QPushButton(self.frame_6)
        self.btnConfiguracion.setGeometry(QtCore.QRect(0, 170, 180, 50))
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(10)
        self.btnConfiguracion.setFont(font)
        self.btnConfiguracion.setCursor(
            QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnConfiguracion.setStyleSheet("QPushButton{\n"
                                            "border:none;\n"
                                            "background: transparent;\n"
                                            "color: #fff;\n"
                                            "padding:10px;\n"
                                            "text-align: left;\n"
                                            "}\n"
                                            "QPushButton:hover{\n"
                                            "background: #4B3869\n"
                                            "}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Iconos/Iconos/Config.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnConfiguracion.setIcon(icon3)
        self.btnConfiguracion.setIconSize(QtCore.QSize(30, 30))
        self.btnConfiguracion.setObjectName("btnConfiguracion")
        self.verticalLayout_2.addWidget(self.frame_6)
        self.horizontalLayout_2.addWidget(self.menuIzquierdo)
        self.menuDerecho = QtWidgets.QFrame(self.frame_2)
        self.menuDerecho.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.menuDerecho.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menuDerecho.setObjectName("menuDerecho")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.menuDerecho)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.paginas = QtWidgets.QStackedWidget(self.menuDerecho)
        self.paginas.setObjectName("paginas")
        self.principal = QtWidgets.QWidget()
        self.principal.setStyleSheet("QWidget{\n"
                                     "background: #fff;\n"
                                     "}")
        self.principal.setObjectName("principal")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.principal)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.principal)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
                                 "background: transparent;\n"
                                 "}")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.paginas.addWidget(self.principal)
        self.usuarios = QtWidgets.QWidget()
        self.usuarios.setStyleSheet("QWidget{\n"
                                    "background: #fff;\n"
                                    "}")
        self.usuarios.setObjectName("usuarios")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.usuarios)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.usuarios)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
                                   "background: transparent;\n"
                                   "}")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.paginas.addWidget(self.usuarios)
        self.configuracion = QtWidgets.QWidget()
        self.configuracion.setStyleSheet("QWidget{\n"
                                         "background: #fff;\n"
                                         "}")
        self.configuracion.setObjectName("configuracion")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.configuracion)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.configuracion)
        font = QtGui.QFont()
        font.setFamily("Verdana")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
                                   "background: transparent;\n"
                                   "}")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3)
        self.paginas.addWidget(self.configuracion)
        self.verticalLayout_3.addWidget(self.paginas)
        self.horizontalLayout_2.addWidget(self.menuDerecho)
        self.verticalLayout.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.frame)
        Principal.setCentralWidget(self.centralwidget)

        self.retranslateUi(Principal)
        self.paginas.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Principal)

    def retranslateUi(self, Principal):
        _translate = QtCore.QCoreApplication.translate
        Principal.setWindowTitle(_translate("Principal", "Menu lateral"))
        self.btnPrincipal.setText(_translate("Principal", "  Principal"))
        self.btnUsuarios.setText(_translate("Principal", "  Usuarios"))
        self.btnConfiguracion.setText(
            _translate("Principal", "  Configuración"))
        self.label.setText(_translate("Principal", "Principal"))
        self.label_2.setText(_translate("Principal", "Usuarios"))
        self.label_3.setText(_translate("Principal", "Configuración"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Principal = QtWidgets.QMainWindow()
    ui = Ui_Principal()
    ui.setupUi(Principal)
    Principal.show()
    sys.exit(app.exec_())
